### ISSUE TITLE
多选样式

### ISSUE THREAD

**Issue by Tsotsi** [code-artisan/selector2#2]
### 多选 有选中项和 为空时的组件高度不一致。
*   addon为button时，
<img width="265" alt="2016-01-14 3 01 10" src="https://cloud.githubusercontent.com/assets/7221340/12317860/1f0eb276-bad0-11e5-87bc-cc4678b2b6cd.png">

**Comment by code-artisan** [comment]
啊哈，我发现这个问题了，现在已经改好了
